jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - env:
          SPONSORS_PAT: ${{ secrets.SPONSORS_PAT }}
        run: GH_TOKEN=$SPONSORS_PAT pnpm build
      - uses: EndBug/add-and-commit@v9

name: Build README.md

on:
  push:
    branches:
      - ci-test
      - main
  repository_dispatch:
    types:
      - webhook
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
