jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: GH_TOKEN=${{ secrets.GITHUB_TOKEN }} pnpm build
      - uses: EndBug/add-and-commit@v9

name: Build README.md

on:
  push:
    branches:
      - ci-test
      - main
